version: '3.8'
services:
    api:
        container_name: "side_project"
        image: "side_project"
        environment:
            - NODE_ENV:${NODE_ENV}
        build:
            context: .
            target: "${NODE_ENV}"
        entrypoint: ["npm", "run", "start:${NODE_ENV}"]
        env_file:
            - .env
        ports:
            - 3000:3000
        volumes:
            - .:/app
            - /app/node_modules
        restart:
            unless-stopped
    mongodb:
        image: mongo:5.0
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=eddy
            - MONGO_INITDB_ROOT_PASSWORD=123456
        volumes:
            - mongodb_data:/data/db
volumes:
    mongodb_data: